Repository TeliaSoneraNorge/styleguide, pull requests merged in 2018-06, with the labels that each got.

#172 Added ToggleSwitch component
  component-lib/src/atoms/ToggleSwitch/ToggleSwitch.jsx
  component-lib/src/atoms/ToggleSwitch/ToggleSwitch.pcss
  component-lib/src/index.js
  src/client/examples/atoms/ToggleSwitch/ToggleSwitch.js
Labels: in progress

#187 Provide bundle with commonjs modules
  component-lib/package.json
  component-lib/rollup.build.js
Labels: enhancement

#185 Add all files from /dist to release
  component-lib/package.json
Labels: bug

#186 Pixelpushing toggleswitch buttons, removed outline on focus and added underline on focus
  component-lib/src/atoms/ToggleSwitch/ToggleSwitch.jsx
  component-lib/src/atoms/ToggleSwitch/ToggleSwitch.pcss
Labels: enhancement
